### ISSUE TITLE
CentOS的源使用帮助，文件内容复制的时候会每行前面多一个空格

### ISSUE THREAD

**Issue by Citron504** [CQUPTMirror/Report#1]
多一个空格，update的时候就会报错。
如果改成那种有一键复制的代码框就好了。
看了一下 Epel和pypi的帮助里面也有这个问题，不知道影不影响。

**Comment by Lich2013** [comment]
@wssgcg1213

**Comment by wssgcg1213** [comment]
@Lich2013 markdown的本身就有空格, 不是前端的问题, 这里的code应该用```包围起来 改一下md吧
