### ISSUE TITLE
Mirror Requests epel and elrepo

### ISSUE THREAD

**Issue by ztelliot** [CQUPTMirror/Report#10]
Mirror Requests
项目名称 epel 和 elrepo
项目简介 RHEL系拓展RPM软件包
上游源地址 https://mirrors.tuna.tsinghua.edu.cn/epel/ 和 https://mirrors.tuna.tsinghua.edu.cn/elrepo/
镜像大小 epel 332.02G elrepo 52.76G

**Comment by Hisssy** [comment]
考虑添加

**Comment by ztelliot** [comment]
比较大，应该有较多人有需求吧，好用的软件大多都在epel里了...

**Comment by eeeeLeeee** [comment]
centos如果木有 epel 简直无法使用。。。。。同求添加

**Comment by eeeeLeeee** [comment]
已经添加了，正在同步，但是他们前端貌似没法暂时出来，直接访问目录能访问到
https://mirrors.redrock.team/epel
https://mirrors.redrock.team/elrepo
