### ISSUE TITLE
Mirror Requests of Anaconda

### ISSUE THREAD

**Issue by jerrita** [CQUPTMirror/Report#11]
请求加入anaconda源
https://mirrors.tuna.tsinghua.edu.cn/help/anaconda/
经常使用

**Comment by eeeeLeeee** [comment]
https://mirrors.tuna.tsinghua.edu.cn/news/restore-anaconda/
你好，请常见上文，我们这边暂时没有开始申请相关授权。
并且从使用率来说，我们暂不确定校内有多少用户需要使用此源。
因此，如果可以，希望你可以让你周边使用该源的同学，也到此issue下做回复，让我们了解到需求量

**Comment by fuckAbdiel** [comment]
> https://mirrors.tuna.tsinghua.edu.cn/news/restore-anaconda/
> 你好，请见上文，我们这边暂时没有开始申请相关授权。
> 并且从使用率来说，我们暂不确定校内有多少用户需要使用此源。
> 因此，如果可以，希望你可以让你周边使用该源的同学，也到此issue下做回复，让我们了解到需求量

**Comment by fuckAbdiel** [comment]
> https://mirrors.tuna.tsinghua.edu.cn/news/restore-anaconda/
> 你好，请见上文，我们这边暂时没有开始申请相关授权。
> 并且从使用率来说，我们暂不确定校内有多少用户需要使用此源。
> 因此，如果可以，希望你可以让你周边使用该源的同学，也到此issue下做回复，让我们了解到需求量

+1000

**Comment by fuckAbdiel** [comment]
> https://mirrors.tuna.tsinghua.edu.cn/news/restore-anaconda/
> 你好，请见上文，我们这边暂时没有开始申请相关授权。
> 并且从使用率来说，我们暂不确定校内有多少用户需要使用此源。
> 因此，如果可以，希望你可以让你周边使用该源的同学，也到此issue下做回复，让我们了解到需求量

+1000

**Comment by eeeeLeeee** [comment]
经咨询，anaconda已经授权大陆高校进行镜像，开始同步拉。
