### ISSUE TITLE
Mirror Requests Docker-CE

### ISSUE THREAD

**Issue by ztelliot** [CQUPTMirror/Report#18]
Mirror Requests
项目名称 docker-ce
项目简介 docker相关软件包
上游源地址 https://mirrors.tuna.tsinghua.edu.cn/docker-ce/
镜像大小 458.16 GB
如果可以，希望能反代下dockerhub

**Comment by Hisssy** [comment]
感谢反馈，近期会加入。

**Comment by Sajotim** [comment]
已经添加

**Comment by ztelliot** [comment]
感谢，但是docker hub的反代存在问题，由于 [*.azk8s.cn 仅限于 Azure China IP 使用，不对外提供服务 ](https://github.com/docker-practice/docker-registry-cn-mirror-test/issues/2#issuecomment-609019328)，因此内网的docker hub镜像实际无法使用，能否考虑更换镜像源，谢谢
