### ISSUE TITLE
希望能请教一下重邮开源镜像问题

### ISSUE THREAD

**Issue by yunshengji** [CQUPTMirror/Report#21]
您好，我是一个在校大学生，就是想请教一下，重邮的tunasync.json 这个文件作为你们首页（http://mirror.cqupt.edu.cn）的数据的来源，是怎么生成的呢？我现在自己也在做一个镜像仓库，但是不知道如何得到像tunasync.json 这样的文件，不太会计算创建之间，大小之类的数据。。。。

**Comment by eeeeLeeee** [comment]
我们的项目很大程度来源于 清华大学tuna协会的项目 你可以参考一下他们的





------------------ 原始邮件 ------------------
发件人: yunsheng ji（吉韵晟） <notifications@github.com&gt;
发送时间: 2020年11月17日 11:23
收件人: CQUPTMirror/Report <Report@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[CQUPTMirror/Report] 希望能请教一下重邮开源镜像问题 (#21)





 
您好，我是一个在校大学生，就是想请教一下，重邮的tunasync.json 这个文件作为你们首页（http://mirror.cqupt.edu.cn）的数据的来源，是怎么生成的呢？我现在自己也在做一个镜像仓库，但是不知道如何得到像tunasync.json 这样的文件，不太会计算创建之间，大小之类的数据。。。。
