### ISSUE TITLE
请求开放同步状态数据的跨域访问

### ISSUE THREAD

**Issue by ZenithalHourlyRate** [CQUPTMirror/Report#27]
同步状态数据的 url 是 https://mirrors.cqupt.edu.cn/static/tunasync.json ，该数据也可用于其他项目（例如 [mirrorz](https://mirrorz.org)），故请求开放其跨域访问，或者几个特定站的跨域访问。

具体方法为添加 `Access-Control-Allow-Origin: *` 的头或者（在`referer: https://mirrorz.org/`时）添加 `Access-Control-Allow-Origin: https://mirrorz.org`

参考 https://github.com/PKUOSC/issues/issues/2

**Comment by Sajotim** [comment]
了解，处理中。

**Comment by ztelliot** [comment]
已允许跨域访问

**Comment by ZenithalHourlyRate** [comment]
注意到贵站的 logo url 似乎是不固定的，形如 https://mirrors.cqupt.edu.cn/img/oss-logo.7bf1d640.svg ，是否有固定的 logo 路径呢。

目前正在填写站点元信息中的 logo 一栏。另：贵站 logo 是否有对暗色模式较为友好的版本（目前来看已经较为友好，不过想问问有没有这种变种）

Update:
发现有 https://mirrors.cqupt.edu.cn/favicon.ico ，但由于部分浏览器不支持将ico作为图片展示，依旧想问问有没有 svg 版本

**Comment by Sajotim** [comment]
> 注意到贵站的 logo url 似乎是不固定的，形如 https://mirrors.cqupt.edu.cn/img/oss-logo.7bf1d640.svg ，是否有固定的 logo 路径呢。
> 
> 目前正在填写站点元信息中的 logo 一栏。另：贵站 logo 是否有对暗色模式较为友好的版本（目前来看已经较为友好，不过想问问有没有这种变种）
> 
> Update:
> 发现有 https://mirrors.cqupt.edu.cn/favicon.ico ，但由于部分浏览器不支持将ico作为图片展示，依旧想问问有没有 svg 版本

https://raw.githubusercontent.com/CQUPTMirror/redlens/master/src/assets/oss-logo.svg
こ↑こ↓

**Comment by ZenithalHourlyRate** [comment]
> https://raw.githubusercontent.com/CQUPTMirror/redlens/master/src/assets/oss-logo.svg

一般用户访问 raw.githubusercontent 还是有点吃力的……我还是先用 favicon 吧

**Comment by ztelliot** [comment]
您也可以使用由jsdelivr提供的cdn https://cdn.jsdelivr.net/gh/CQUPTMirror/redlens/src/assets/oss-logo.svg

此外，建议您将我们的地址改成 https://mirrors.redrock.team ，https://mirrors.cqupt.edu.cn 由教育网提供服务， https://mirrors.redrock.team 由电信提供服务

**Comment by ZenithalHourlyRate** [comment]
```
$ cat cqupt.json
{
    "url": "https://mirrors.redrock.team",
    "logo": "https://mirrors.cqupt.edu.cn/favicon.ico",
    "abbr": "CQUPT",
    "name": "重庆邮电大学开源镜像站",
    "homepage": "https://redrock.team",
    "issue": "https://github.com/CQUPTMirror/Report",
    "request": "https://github.com/CQUPTMirror/Report"
}
```
目前相关元数据是这样的，还需要进行哪些改动呢
完整的元数据格式参考 https://github.com/tuna/mirrorz/blob/master/README.md#data-format-v14-draft

**Comment by ztelliot** [comment]
您可以再加上我们的邮箱 sre@redrock.team 和 tg 群 https://t.me/joinchat/UdfEDoBWUpZmNmNl
