### ISSUE TITLE
Mirror Request - AUR

### ISSUE THREAD

**Issue by usamoi** [CQUPTMirror/Report#28]
* 项目名称：AUR
* 项目简介：Arch Linux用户社区仓库。
* 源：https://aur.archlinux.org/

**Comment by Sajotim** [comment]
已知悉，预计6月20日上线

**Comment by ztelliot** [comment]
您好，我们已对 AUR 进行了反代，您可以通过 https://aur.redrock.team/ 访问，镜像站前端将在未来几天更新
