### ISSUE TITLE
看不懂的主页资源排序方式

### ISSUE THREAD

**Issue by berlin2123** [CQUPTMirror/Report#29]
每次打开主页，资源列表的显示顺序都不一样。看不懂的排序方式。为“找是否有需要的资源”制造困难。当然可以说：可以 Ctrl+F 找啊。

**Comment by Hisssy** [comment]
目前没有固定排序，需要啥可以在右边的搜索框找

**Comment by Hisssy** [comment]
目前没有固定排序，需要啥可以在右边的搜索框找

**Comment by qwqVictor** [comment]
![image](https://user-images.githubusercontent.com/21100901/127986336-5fb3fd40-8024-47ab-afec-c87ecc300550.png)
现在已经按照字典序展示主页资源了，感谢建议。
