### ISSUE TITLE
希望增加 SteamOS 镜像

### ISSUE THREAD

**Issue by wbsdty331** [CQUPTMirror/Report#3]
SteamOS 是基于 Debian 的一个发行版
上游是 ：http://repo.steampowered.com/
由于国内网络原因加上Valve CDN的问题，下载安装光盘很缓慢，更新软件包也经常出错
希望添加，谢谢！

**Comment by zfox49** [comment]
感谢反馈
但是由于 我校 LUG 无人使用 SteamOS，我们无法保证 搭建好之后 StamOS 的可靠性。
以及目前我们的 mirror 磁盘容量接近饱和，所以需要等待下一批机器。
建议先食用 https://mirrors.ustc.edu.cn/steamos/
