### ISSUE TITLE
PyPI反向代理问题

### ISSUE THREAD

**Issue by koiking129** [CQUPTMirror/Report#30]
torchinfo这个包好像没跟官网同步？
缺少很多版本，而且现有的最高版本**1.4.4**还刚好是*YANKED*
PyPI官网和清华源的最新版本一致，都为1.5.2
系统状态里显示PyPI正常同步(🙂)

重邮源的torchinfo包：<https://mirrors.cqupt.edu.cn/pypi/simple/torchinfo/>
清华源的torchinfo包：<https://pypi.tuna.tsinghua.edu.cn/simple/torchinfo/>
PyPI的torchinfo包：<https://pypi.org/project/torchinfo/#history>

**Comment by Sajotim** [comment]
问题已经排查 目前正在重新全量同步中

**Comment by ztelliot** [comment]
全量同步已经完成 torchinfo 包版本已与官方保持一致
