### ISSUE TITLE
申请新镜像

### ISSUE THREAD

**Issue by Smart-SangGe** [CQUPTMirror/Report#31]
f-droid
官网为https://www.f-droid.org/
简介：F-Droid is an installable catalogue of FOSS (Free and Open Source Software) applications for the Android platform. The client makes it easy to browse, install, and keep track of updates on your device.
配置镜像：https://f-droid.org/en/docs/Running_a_Mirror/

**Comment by ztelliot** [comment]
您好，我们已完成 fdroid 的同步，您可以在 F-Droid 客户端中通过下方链接添加用户镜像

https://mirrors.cqupt.edu.cn/fdroid/repo/?fingerprint=43238D512C1E5EB2D6569F4A3AFBF5523418B82E0A3ED1552770ABB9A9C9CCAB

https://mirrors.cqupt.edu.cn/fdroid/archive?fingerprint=43238D512C1E5EB2D6569F4A3AFBF5523418B82E0A3ED1552770ABB9A9C9CCAB
