### ISSUE TITLE
anaconda无法创建虚拟环境

### ISSUE THREAD

**Issue by li-pengcheng** [CQUPTMirror/Report#32]
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pip-21.2.2                 |   py36h06a4308_0         2.1 MB  defaults
    ncurses-6.3                |       heee7806_1         1.0 MB  defaults
    python-3.6.13              |       h12debd9_1        32.5 MB  defaults
    setuptools-58.0.4          |   py36h06a4308_0         979 KB  defaults
    certifi-2021.5.30          |   py36h06a4308_0         141 KB  defaults
    ------------------------------------------------------------
                                           Total:        36.7 MB

The following NEW packages will be INSTALLED:

    _libgcc_mutex:    0.1-main                 defaults
    ca-certificates:  2021.10.26-h06a4308_2    defaults
    certifi:          2021.5.30-py36h06a4308_0 defaults
    ld_impl_linux-64: 2.35.1-h7274673_9        defaults
    libffi:           3.3-he6710b0_2           defaults
    libgcc-ng:        9.1.0-hdf63c60_0         defaults
    libstdcxx-ng:     9.1.0-hdf63c60_0         defaults
    ncurses:          6.3-heee7806_1           defaults
    openssl:          1.1.1l-h7f8727e_0        defaults
    pip:              21.2.2-py36h06a4308_0    defaults
    python:           3.6.13-h12debd9_1        defaults
    readline:         8.1-h27cfd23_0           defaults
    setuptools:       58.0.4-py36h06a4308_0    defaults
    sqlite:           3.36.0-hc218d9a_0        defaults
    tk:               8.6.11-h1ccaba5_0        defaults
    wheel:            0.37.0-pyhd3eb1b0_1      defaults
    xz:               5.2.5-h7b6447c_0         defaults
    zlib:             1.2.11-h7b6447c_3        defaults

Proceed ([y]/n)? y

Downloading and Extracting Packages
pip-21.2.2           | 2.1 MB    | #################################################################################################################################################### | 100%
ncurses-6.3          | 1.0 MB    |                                                                                                                                                      |   0%
python-3.6.13        | 32.5 MB   | #################################################################################################################################################### | 100%
setuptools-58.0.4    | 979 KB    | #################################################################################################################################################### | 100%
certifi-2021.5.30    | 141 KB    | #################################################################################################################################################### | 100%

CondaHTTPError: HTTP 404 NOT FOUND for url <https://mirrors.cqupt.edu.cn/anaconda/pkgs/main/linux-64/ncurses-6.3-heee7806_1.tar.bz2>
Elapsed: 00:00.031892

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

**Comment by Sajotim** [comment]
已经处理，麻烦重新尝试一下。
有问题可以 Reopen
