### ISSUE TITLE
Arm ubuntu can't be supported well.

### ISSUE THREAD

**Issue by tommyme** [CQUPTMirror/Report#34]
I'm currently using Arm ubuntu, and when i'm using cqupt mirror, I get error like this:
ENV: 
- m1 macbook pro
- docker
```
E: The repository 'https://mirrors.cqupt.edu.cn/ubuntu-ports focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: https://mirrors.cqupt.edu.cn/ubuntu-ports/dists/focal-updates/Release: No system certificates available. Try installing ca-certificates.
```
please fix it.

**Comment by qwqVictor** [comment]
Looks like that your system is installed without some basic packages like `ca-certificates`.  
Try to use HTTP protocol first and install `ca-certificates`, and then switch back to HTTPS protocol.
Hope it could help.

**Comment by tommyme** [comment]
yep, It's Right, Thank you.

**Comment by tommyme** [comment]
but why TsingHua's mirror can be used without `https` & `ca-certificates`. [/doge]
