### ISSUE TITLE
homebrew mirror is down.

### ISSUE THREAD

**Issue by tommyme** [CQUPTMirror/Report#35]
http://mirrors.cqupt.edu.cn/homebrew/ is a 404 page. It can't work any more.

**Comment by ZenithalHourlyRate** [comment]
> 重庆邮电大学开源镜像站所属于的红岩网校工作站服务器整体架构正在升级迭代，在此期间为了提供服务，我们综合考虑，反向代理了 北京外国语大学开源镜像站。

对于 bfsu homebrew，使用方法可参考 https://mirrors.bfsu.edu.cn/help/homebrew/
