### ISSUE TITLE
申请新镜像-PYG

### ISSUE THREAD

**Issue by Luotas** [CQUPTMirror/Report#37]
希望在Anaconda/cloud中增加PYG的镜像

官网为 https://www.pyg.org/
简介：PyG is a library built upon PyTorch to easily write and train Graph Neural Networks for a wide range of applications related to structured data. PyG is both friendly to machine learning researchers and first-time users of machine learning toolkits.
配置镜像：https://anaconda.org/pyg/repo
上游源地址：https://github.com/pyg-team/pytorch_geometric

**Comment by ztelliot** [comment]
非常抱歉，由于之前镜像站重建，各项镜像重新同步耗时过长，以致 anaconda 镜像仍未同步完成，pyg 我们已于此前加入同步列表，在同步完成后我们将再向您更新，感谢您对我们的支持与理解。

**Comment by ztelliot** [comment]
您好，我们已完成对 anaconda 的同步，您可以从 https://mirrors.cqupt.edu.cn/anaconda/cloud/pyg/ 获取 pyg 的相关内容，谢谢。

**Comment by Luotas** [comment]
感谢你们的做出努力，谢谢你们。

**Comment by Luotas** [comment]
我把pyg的源加入到 .condarc 中后，

ssl_verify: true
channel_alias: https://mirrors.cqupt.edu.cn/anaconda/
channels:
  - https://mirrors.cqupt.edu.cn/anaconda/cloud/pytorch
  - https://mirrors.cqupt.edu.cn/anaconda/cloud/dglteam
  - https://mirrors.cqupt.edu.cn/anaconda/cloud/Paddle
  - https://mirrors.cqupt.edu.cn/anaconda/cloud/pyg
  - https://mirrors.cqupt.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.cqupt.edu.cn/anaconda/pkgs/free
  - https://mirrors.cqupt.edu.cn/anaconda/pkgs/main
  - https://mirrors.cqupt.edu.cn/anaconda/pkgs/mro
  - https://mirrors.cqupt.edu.cn/anaconda/pkgs/msys2
  - https://mirrors.cqupt.edu.cn/anaconda/pkgs/pro
  - https://mirrors.cqupt.edu.cn/anaconda/pkgs/r

提示错误如下：

PS C:\Users\Yang> conda update --all
Collecting package metadata (current_repodata.json): failed

UnavailableInvalidChannel: The channel is not accessible or is invalid.
  channel name: cloud/pyg
  channel url: https://mirrors.cqupt.edu.cn/anaconda/cloud/pyg
  error code: 404

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state,
and use `conda config --show-sources` to view config file locations.

**Comment by ztelliot** [comment]
您好，经过排查我们发现是由于 noarch 无文件导致，现在已经修复，感谢支持。

**Comment by Luotas** [comment]
感谢你们。。
