### ISSUE TITLE
Anaconda镜像源

### ISSUE THREAD

**Issue by li-pengcheng** [CQUPTMirror/Report#38]
channels:
  - defaults
show_channel_urls: true
channel_alias: https://mirrors.cqupt.edu.cn/anaconda
default_channels:
  - https://mirrors.cqupt.edu.cn/anaconda/pkgs/main
  - https://mirrors.cqupt.edu.cn/anaconda/pkgs/free
  - https://mirrors.cqupt.edu.cn/anaconda/pkgs/r
  - https://mirrors.cqupt.edu.cn/anaconda/pkgs/pro
  - https://mirrors.cqupt.edu.cn/anaconda/pkgs/msys2
custom_channels:
  conda-forge: https://mirrors.cqupt.edu.cn/anaconda/cloud
  msys2: https://mirrors.cqupt.edu.cn/anaconda/cloud
  bioconda: https://mirrors.cqupt.edu.cn/anaconda/cloud
  menpo: https://mirrors.cqupt.edu.cn/anaconda/cloud
  pytorch: https://mirrors.cqupt.edu.cn/anaconda/cloud
  simpleitk: https://mirrors.cqupt.edu.cn/anaconda/cloud

anaconda配置如上，但一直无法正常使用，创建环境显示
Solving environment: failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://mirrors.cqupt.edu.cn/anaconda/pkgs/pro/noarch/repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ConnectionError(MaxRetryError("HTTPSConnectionPool(host='mirrors.cqupt.edu.cn', port=443): Max retries exceeded with url: /anaconda/pkgs/pro/noarch/repodata.json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd64835c390>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))"))

**Comment by ztelliot** [comment]
> Temporary failure in name resolution

您好，根据报错信息显示，域名解析失败，建议您优先排查本机 DNS 设置。

**Comment by li-pengcheng** [comment]
DNS设置没有问题，我目前的解决方案是将所有https替换为http，然后就正常了。

**Comment by Sajotim** [comment]
> DNS设置没有问题，我目前的解决方案是将所有https替换为http，然后就正常了。

在你提供的日志最后一行
Temporary failure in name resolution![image](https://user-images.githubusercontent.com/20022853/170513242-dbbd0646-02f6-407a-ae39-085aefe4f3d7.png)
这种情况我们一般是认为DNS有问题，当然不一定是配置错误，可能是CQUPT的内网DNS挂了。
虽然问题解决的很“Magic”，不过能用就好，但是还是建议更换为更稳定的DNS服务。
