### ISSUE TITLE
Service Issues:ubuntu 18.04 apt-get update error

### ISSUE THREAD

**Issue by Difers** [CQUPTMirror/Report#39]
Issue description:
root@ai:/etc/apt# apt update
Hit:1 http://mirrors.cqupt.edu.cn/ubuntu bionic InRelease
Get:2 http://mirrors.cqupt.edu.cn/ubuntu bionic-security InRelease [88.7 kB]
Hit:3 http://mirrors.cqupt.edu.cn/ubuntu bionic-updates InRelease
Hit:4 http://mirrors.cqupt.edu.cn/ubuntu bionic-proposed InRelease
Hit:5 http://mirrors.cqupt.edu.cn/ubuntu bionic-backports InRelease
Ign:6 http://mirrors.cqupt.edu.cn/ubuntu bionic-security/universe Sources
Get:7 http://mirrors.cqupt.edu.cn/ubuntu bionic-security/multiverse Sources [8784 B]
Get:8 http://mirrors.cqupt.edu.cn/ubuntu bionic-security/restricted Sources [28.0 kB]
Get:9 http://mirrors.cqupt.edu.cn/ubuntu bionic-security/main Sources [337 kB]
Get:10 http://mirrors.cqupt.edu.cn/ubuntu bionic-security/restricted amd64 Packages [885 kB]
Get:11 http://mirrors.cqupt.edu.cn/ubuntu bionic-security/multiverse amd64 Packages [21.1 kB]
Get:12 http://mirrors.cqupt.edu.cn/ubuntu bionic-security/main amd64 Packages [2696 kB]
Get:13 http://mirrors.cqupt.edu.cn/ubuntu bionic-security/universe amd64 Packages [1490 kB]
Get:6 http://mirrors.cqupt.edu.cn/ubuntu bionic-security/universe Sources [368 kB]
Err:6 http://mirrors.cqupt.edu.cn/ubuntu bionic-security/universe Sources
  File has unexpected size (367549 != 367533). Mirror sync in progress? [IP: 202.202.43.25 80]
  Hashes of expected file:
   - Filesize:367533 [weak]
   - SHA256:b5673848d3f761d4edbb02bb4b74989bdcaf92679f69fab2f296c15a19a4a334
   - SHA1:a30f21a60e871df62b7ddb8687f2ee7044fea148 [weak]
   - MD5Sum:81ad05c7698c5c4fa1673b07661df18b [weak]
  Release file created at: Tue, 19 Apr 2022 14:54:31 +0000
Reading package lists... Done
E: Failed to fetch http://mirrors.cqupt.edu.cn/ubuntu/dists/bionic-security/universe/source/Sources.gz  File has unexpected size (367549 != 367533). Mirror sync in progress? [IP: 202.202.43.25 80]
   Hashes of expected file:
    - Filesize:367533 [weak]
    - SHA256:b5673848d3f761d4edbb02bb4b74989bdcaf92679f69fab2f296c15a19a4a334
    - SHA1:a30f21a60e871df62b7ddb8687f2ee7044fea148 [weak]
    - MD5Sum:81ad05c7698c5c4fa1673b07661df18b [weak]
   Release file created at: Tue, 19 Apr 2022 14:54:31 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by qwqVictor** [comment]
Thank you for the report. Actually the ubuntu mirror currently has some syncing issues, we are digging on it.
