### ISSUE TITLE
CentOS 7.5 更新失败

### ISSUE THREAD

**Issue by MakingL** [CQUPTMirror/Report#4]
**CentOS 7.5** 更换源后，发现不支持。由于校内Linux联网方式严重受限，希望能够支持CentOS 7.5的源。

`Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
http://centos.mirrors.cqupt.edu.cn/7/os/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below wiki article 

https://wiki.centos.org/yum-errors

If above article doesn't help to resolve this issue please use https://bugs.centos.org/.

`

**Comment by qnnnnez** [comment]
文档中有一些错误。文档里写的镜像源的子域名 URL 已经停止使用了。现在的正确 URL 应该是 http://mirrors.cqupt.edu.cn/centos/

已更新了 CentOS 的帮助文档：
https://github.com/CQUPTMirror/cqupt-mirrors-howto/blob/master/centos-mirror-howto.md

本地测试可以正常使用，关闭 issue。如果使用过程种有任何问题欢迎随时重新 open。

**Comment by MakingL** [comment]
OK 谢谢
