### ISSUE TITLE
[Mirror Request] Termux

### ISSUE THREAD

**Issue by 2096779623** [CQUPTMirror/Report#43]
- name: `Termux`
- intro_link: <https://termux.dev>
- storage_link: <https://packages.termux.dev>
- licence:https://github.com/termux/termux-packages/blob/master/LICENSE.md
- size:19GB

## descrption and reasons

Termux 是一款Android 终端模拟器和 Linux 环境应用程序，无需 root 或设置即可直接运行。自动安装最小的基本系统 - 使用 APT 包管理器可以使用其他包。

同步方式请查看这个链接：https://github.com/termux/termux-packages/wiki/How-to-mirror-the-official-repositories

**Comment by ztelliot** [comment]
您好，我们已经完成对 termux 的同步，您可以通过 https://mirrors.cqupt.edu.cn/termux/ 访问 termux 镜像。
