### ISSUE TITLE
给个nix谢谢喵

### ISSUE THREAD

**Issue by jerrita** [CQUPTMirror/Report#44]
如题

**Comment by ztelliot** [comment]
同学你好，我们已经完成对 nix 的同步，你可以通过 https://mirrors.cqupt.edu.cn/nix/ 访问 nix 镜像。

**Comment by eeeeLeeee** [comment]
链接调整有问题，注意检查下配置
&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CQUPTMirror/Report"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月17日(星期二) 下午2:35
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [CQUPTMirror/Report] 给个nix谢谢喵 (Issue #44)





 
同学你好，我们已经完成对 nix 的同步，你可以通过 https://mirrors.cqupt.edu.cn/nix/ 访问 nix 镜像。

**Comment by ztelliot** [comment]
> 链接调整有问题，注意检查下配置

fixed

**Comment by jerrita** [comment]
> 同学你好，我们已经完成对 nix 的同步，你可以通过 https://mirrors.cqupt.edu.cn/nix/ 访问 nix 镜像。

emmm，有用到的应该是 channels，可以参考下这个

http://mirrors.ustc.edu.cn/help/nix-channels.html

**Comment by jerrita** [comment]
镜像过大，关闭
