### ISSUE TITLE
mirrors.redrock.team域名证书部署有问题

### ISSUE THREAD

**Issue by newton-miku** [CQUPTMirror/Report#46]
似乎[mirrors.redrock.team](https://mirrors.redrock.team/)的域名部署有问题，证书是使用的edu的域名证书
其次，该域名看起来是直接重定向到edu的域名的，这样可能会导致并没有起到加速的效果

**Comment by ztelliot** [comment]
您好，当前我们通过 GeoDNS 自动选择节点，使用 https://mirrors.cqupt.edu.cn 即可
