### ISSUE TITLE
可以多开一个dockerhub镜像源吗

### ISSUE THREAD

**Issue by changzee** [CQUPTMirror/Report#49]
如题

**Comment by eeeeLeeee** [comment]
想多了吧





------------------ 原始邮件 ------------------
发件人: changzee ***@***.***&gt;
发送时间: 2024年6月19日 11:01
收件人: CQUPTMirror/Report ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [CQUPTMirror/Report] 可以多开一个dockerhub镜像源吗 (Issue #49)
