### ISSUE TITLE
镜像站无法访问

### ISSUE THREAD

**Issue by STRRL** [CQUPTMirror/Report#5]
您好：
您的镜像站出现在了nrm的列表中，但无法访问。
同时mirror.cqupt.edu.cn也无法访问。
现在镜像站只对贵校校内开放吗？

网络环境：
云南教育网

**Comment by qnnnnez** [comment]
是的。非常抱歉，学校网络中心现在不给开互联网访问了，我们尝试沟通无果，所以我们现阶段无法对校外用户提供服务了。

**Comment by eeeeLeeee** [comment]
nrm上的url是用的proxy地址？ @qnnnnez
