### ISSUE TITLE
页面打不开了

### ISSUE THREAD

**Issue by leogorden** [CQUPTMirror/Report#6]
页面打不开了，
http://mirrors.cqupt.edu.cn/
是放弃维护了吗

**Comment by qnnnnez** [comment]
我们的镜像站现在只有内网才能访问了。

https://github.com/CQUPTMirror/Report/issues/5

**Comment by leogorden** [comment]
哦哦，我还以为是外网也可以访问的，作为我大重邮的毕业生，希望有朝一日镜像可以对外开放

**Comment by eeeeLeeee** [comment]
https://mirrors.redrock.team 现在又有外网了
