### ISSUE TITLE
可以添加一下ros-kinetic的镜像吗

### ISSUE THREAD

**Issue by Garry101CN** [CQUPTMirror/Report#8]
可以添加一下ros-kinetic版本的镜像吗，其他源都很慢

**Comment by eeeeLeeee** [comment]
你好，能否提供一下官网 上游 以及一些介绍？便于我们镜像

**Comment by eeeeLeeee** [comment]
看了下应该是：https://mirrors.tuna.tsinghua.edu.cn/ros/
麻烦确认下。

**Comment by eeeeLeeee** [comment]
已经添加
