### ISSUE TITLE
Mirror Requests-AOSP

### ISSUE THREAD

**Issue by yukitsu-ren** [CQUPTMirror/Report#9]
Mirror Requests
    项目名称 AOSP
    项目简介 Android源代码
    上游源地址 https://aosp.tuna.tsinghua.edu.cn/ 使用方法https://mirrors.tuna.tsinghua.edu.cn/help/AOSP/
    镜像大小约164GB

**Comment by qnnnnez** [comment]
TUNA 搞了按月更新的离线包 aosp-monthly，只镜像这个可以吗？
能否具体说下使用需求，比如有多少人需要使用，对更新的实时性要求怎样，这样可以方便我们统筹规划
